tunnel: 52ea5dd5-66b3-4192-9e04-344aee7c2a0b
credentials-file: /Users/n4vn/.cloudflared/52ea5dd5-66b3-4192-9e04-344aee7c2a0b.json
protocol: http2


ingress:
  - hostname: operation1.n4vn.space
    service: http://localhost:3000
  - hostname: ssh.n4vn.space
    service: ssh://localhost:22
  - service: http_status:404

# To connect to this machine via SSH, add the following to your ~/.ssh/config:
# Host ssh.n4vn.space
#   User n4vn
#   ProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h
